/* =============================================================================
   Trading Journal v1 — prototype application

   Reads window.JOURNAL (generated by scripts/build_synthetic.py from the SQLite
   database) and renders the eight specified screens. No framework, no network,
   no build step: open index.html.

   Everything on screen is synthetic placeholder data.
   ============================================================================= */
(function () {
  "use strict";

  var D = window.JOURNAL;
  var ET_OFFSET_MS = 4 * 3600 * 1000; // stored UTC -> America/New_York wall clock (EDT)

  /* ------------------------------------------------------------------ format */
  var MONTHS = ["January", "February", "March", "April", "May", "June", "July",
                "August", "September", "October", "November", "December"];
  var DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  var MINUS = "−";

  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }
  function pad(n) { return (n < 10 ? "0" : "") + n; }

  function etDate(iso) {
    if (!iso) return null;
    return new Date(Date.parse(iso) - ET_OFFSET_MS);
  }
  function etTime(iso) {
    var d = etDate(iso);
    return d ? pad(d.getUTCHours()) + ":" + pad(d.getUTCMinutes()) : "";
  }
  function dayName(ymd) {
    var p = ymd.split("-");
    return DAYS[new Date(Date.UTC(+p[0], +p[1] - 1, +p[2])).getUTCDay()];
  }
  function longDate(ymd) {
    var p = ymd.split("-");
    return dayName(ymd) + " " + (+p[2]) + " " + MONTHS[+p[1] - 1] + " " + p[0];
  }
  function shortDate(ymd) {
    var p = ymd.split("-");
    return (+p[2]) + " " + MONTHS[+p[1] - 1].slice(0, 3);
  }

  function sgn(v) { return v == null ? "flat" : (v > 0.0001 ? "pos" : (v < -0.0001 ? "neg" : "flat")); }
  function cls(v) { return "v-" + sgn(v); }

  function fmtR(v, dp) {
    if (v == null) return "—";
    var n = Math.abs(v).toFixed(dp == null ? 2 : dp);
    return (v > 0.0001 ? "+" : v < -0.0001 ? MINUS : "") + n + "R";
  }
  function fmtMoney(v) {
    if (v == null) return "—";
    var n = Math.abs(v).toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    return (v > 0.0001 ? "+" : v < -0.0001 ? MINUS : "") + "$" + n;
  }
  function fmtNum(v, dp) { return v == null ? "—" : Number(v).toFixed(dp == null ? 1 : dp); }
  function fmtPx(v) { return v == null ? "—" : Number(v).toFixed(2); }
  function fmtDur(s) {
    if (s == null) return "—";
    var m = Math.round(s / 60);
    return m >= 60 ? Math.floor(m / 60) + "h " + (m % 60) + "m" : m + "m";
  }
  /* Outcome words. Colour is never the only carrier — every signed number is
     paired with its sign, and every state chip carries a word. */
  /* Rounded to the displayed precision first, so a 0.002 rounding residue never
     renders as "+0.00R, discretion added". */
  function deltaR(actual, mech) {
    if (actual == null || mech == null) return null;
    return Math.round((actual - mech) * 100) / 100;
  }
  function deltaWord(d) {
    if (d == null) return "no reference";
    if (Math.abs(d) < 0.005) return "matched the rules";
    return d > 0 ? "discretion added" : "discretion cost";
  }
  function outcomeWord(r) { return r == null ? "no result" : r > 0.0001 ? "gain" : r < -0.0001 ? "loss" : "scratch"; }

  /* deterministic PRNG so generated chart paths never move between renders */
  function seeded(str) {
    var h = 2166136261;
    for (var i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 16777619); }
    return function () {
      h += 0x6D2B79F5; var t = h;
      t = Math.imul(t ^ (t >>> 15), t | 1);
      t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }

  /* ------------------------------------------------------------------ data access */
  var SESSIONS = D.sessions.slice().sort(function (a, b) { return a.date < b.date ? -1 : 1; });
  var BY_DATE = {};
  var TRADES = [];
  SESSIONS.forEach(function (s) {
    BY_DATE[s.date] = s;
    s.trades.forEach(function (t) { t._session = s; TRADES.push(t); });
  });
  var TRADE_BY_UID = {};
  TRADES.forEach(function (t) { TRADE_BY_UID[t.trade_uid] = t; });
  var TODAY = D.meta.today;
  var TAXONOMY = {};
  D.mistake_taxonomy.forEach(function (m) { TAXONOMY[m.code] = m; });

  function tagLabel(code) { return TAXONOMY[code] ? TAXONOMY[code].label : code; }
  function m(s) { return s.metrics || {}; }

  function weeksDesc() {
    var seen = [];
    SESSIONS.forEach(function (s) { if (seen.indexOf(s.iso_week) < 0) seen.push(s.iso_week); });
    return seen.reverse();
  }
  function monthsDesc() {
    var seen = [];
    SESSIONS.forEach(function (s) { if (seen.indexOf(s.iso_month) < 0) seen.push(s.iso_month); });
    return seen.reverse();
  }
  function sessionsIn(key, field) {
    return SESSIONS.filter(function (s) { return s[field] === key; });
  }

  function aggregate(list) {
    var a = {
      sessions: list.length, trades: 0, wins: 0, losses: 0, r: 0, net: 0,
      opps: 0, taken: 0, missed: 0, mech: 0, uva: 0, mistakes: 0,
      process: [], adherence: [], grossWin: 0, grossLoss: 0, maxDD: 0, noTrade: 0
    };
    var run = 0, peak = 0;
    list.forEach(function (s) {
      var mm = m(s);
      a.trades += mm.trade_count || 0;
      a.wins += mm.win_count || 0;
      a.losses += mm.loss_count || 0;
      a.r += mm.total_r || 0;
      a.net += mm.net_pnl || 0;
      a.opps += mm.opportunities_total || 0;
      a.taken += mm.opportunities_taken || 0;
      a.missed += mm.opportunities_missed || 0;
      a.mech += mm.mechanical_r || 0;
      a.uva += mm.user_value_added_r || 0;
      a.mistakes += mm.mistake_count || 0;
      if (mm.process_score != null) a.process.push(mm.process_score);
      if (mm.rule_adherence != null) a.adherence.push(mm.rule_adherence);
      if (!mm.trade_count) a.noTrade++;
      s.trades.forEach(function (t) {
        if (t.r_multiple > 0) a.grossWin += t.r_multiple;
        else a.grossLoss += Math.abs(t.r_multiple || 0);
      });
      run += mm.total_r || 0;
      peak = Math.max(peak, run);
      a.maxDD = Math.min(a.maxDD, run - peak);
    });
    a.avgProcess = a.process.length ? a.process.reduce(function (x, y) { return x + y; }, 0) / a.process.length : null;
    a.avgAdherence = a.adherence.length ? a.adherence.reduce(function (x, y) { return x + y; }, 0) / a.adherence.length : null;
    a.expectancy = a.trades ? a.r / a.trades : null;
    a.pf = a.grossLoss > 0 ? a.grossWin / a.grossLoss : null;
    a.winRate = a.trades ? (a.wins / a.trades) * 100 : null;
    a.takeRate = a.opps ? (a.taken / a.opps) * 100 : null;
    return a;
  }

  /* ------------------------------------------------------------------ components */
  function stat(k, v, sub, klass) {
    return '<div class="stat"><span class="k">' + esc(k) + '</span>' +
      '<span class="v ' + (klass || "") + '">' + v + "</span>" +
      (sub ? '<span class="s">' + sub + "</span>" : "") + "</div>";
  }

  function dial(score, label) {
    if (score == null) return "";
    var r = 26, c = 2 * Math.PI * r, on = c * (score / 100);
    return '<div class="dial">' +
      '<svg width="64" height="64" viewBox="0 0 64 64" role="img" aria-label="Process score ' +
        fmtNum(score, 0) + ' out of 100">' +
      '<circle cx="32" cy="32" r="' + r + '" fill="none" stroke="var(--card-3)" stroke-width="5"/>' +
      '<circle cx="32" cy="32" r="' + r + '" fill="none" stroke="var(--accent)" stroke-width="5" ' +
        'stroke-linecap="round" stroke-dasharray="' + on.toFixed(1) + " " + c.toFixed(1) + '" ' +
        'transform="rotate(-90 32 32)"/></svg>' +
      '<div><div class="dial-v">' + fmtNum(score, 0) + '<span class="muted" style="font-size:13px">/100</span></div>' +
      '<div class="dial-l">' + esc(label || "Process score") + "</div></div></div>";
  }

  function pips(n, max, warm) {
    var out = '<span class="pips">';
    for (var i = 1; i <= (max || 5); i++) {
      out += '<span class="pip' + (i <= n ? " on" + (warm ? " warm" : "") : "") + '"></span>';
    }
    return out + "</span>";
  }

  function rating(label, value, warm) {
    if (value == null) return "";
    return '<div class="rating"><span class="lbl">' + esc(label) + "</span>" +
      '<span class="row" style="gap:8px">' + pips(value, 5, warm) +
      '<span class="n">' + value + "/5</span></span></div>";
  }

  function tagChips(tags) {
    if (!tags || !tags.length) return '<span class="chip chip-ghost">no flags</span>';
    return tags.map(function (t) {
      return '<span class="chip chip-flag" title="' + esc((TAXONOMY[t] || {}).description || "") + '">' +
        esc(tagLabel(t)) + "</span>";
    }).join(" ");
  }

  var OPP_WORDS = {
    TAKEN: ["taken", "chip-accent"], BOT_EXECUTED: ["bot executed", "chip-accent"],
    MISSED: ["missed", "chip-watch"], BOT_FAILED: ["bot failed", "chip-flag"],
    SKIPPED_BY_RULE: ["skipped by rule", "chip"], SKIPPED_DISCRETIONARY: ["skipped by choice", "chip"],
    INVALIDATED: ["invalidated", "chip"], NO_ACTION: ["no action", "chip"]
  };
  function oppChip(status) {
    var w = OPP_WORDS[status] || [status.toLowerCase(), "chip"];
    return '<span class="chip ' + (w[1] === "chip" ? "chip-ghost" : w[1]) + '">' + esc(w[0]) + "</span>";
  }

  /* ------------------------------------------------------------------ charts */

  /* Synthetic intrabar path. Production replaces this with the captured chart
     image referenced by media_asset; the geometry (entry/stop/target/MFE/MAE)
     is identical either way. */
  function pricePath(t, n) {
    var rand = seeded(t.trade_uid), dir = t.side === "long" ? 1 : -1;
    var risk = Math.abs(t.avg_entry_price - t.initial_stop) || 4;
    var mfe = t.mfe_r == null ? 0.6 : t.mfe_r, mae = t.mae_r == null ? -0.4 : t.mae_r;
    var rr = t.r_multiple == null ? 0 : t.r_multiple;
    var pre = Math.round(n * 0.22), post = Math.round(n * 0.18);
    var hold = n - pre - post;
    var pts = [], i;

    var p = t.avg_entry_price - dir * risk * (0.35 + rand() * 0.3);
    for (i = 0; i < pre; i++) {
      p += (t.avg_entry_price - p) * 0.28 + (rand() - 0.5) * risk * 0.16;
      pts.push(p);
    }
    pts.push(t.avg_entry_price);

    // order the excursions so the path is legible: adverse first on winners,
    // favourable first on losers — the usual shape of a trade that works or doesn't.
    var legs = rr >= 0
      ? [[0.30, mae], [0.72, mfe], [1.0, rr]]
      : [[0.34, mfe], [0.78, mae], [1.0, rr]];
    var prevIdx = 0, prevR = 0, mfeIdx = 0, maeIdx = 0, best = -1e9, worst = 1e9;
    legs.forEach(function (leg) {
      var idx = Math.max(1, Math.round(hold * leg[0]));
      for (var k = prevIdx + 1; k <= idx; k++) {
        var f = (k - prevIdx) / (idx - prevIdx);
        var rv = prevR + (leg[1] - prevR) * (f * f * (3 - 2 * f));
        pts.push(t.avg_entry_price + dir * risk * rv + (rand() - 0.5) * risk * 0.1);
      }
      prevIdx = idx; prevR = leg[1];
    });
    var entryIdx = pre, exitIdx = pts.length - 1;
    for (i = entryIdx; i <= exitIdx; i++) {
      var rel = (pts[i] - t.avg_entry_price) * dir;
      if (rel > best) { best = rel; mfeIdx = i; }
      if (rel < worst) { worst = rel; maeIdx = i; }
    }
    p = pts[pts.length - 1];
    for (i = 0; i < post; i++) {
      p += (rand() - 0.5) * risk * 0.3;
      pts.push(p);
    }
    return { pts: pts, entryIdx: entryIdx, exitIdx: exitIdx, mfeIdx: mfeIdx, maeIdx: maeIdx };
  }

  function tradeChart(t, opts) {
    opts = opts || {};
    var W = opts.w || 216, H = opts.h || 132, P = opts.pad || (opts.big ? 34 : 8);
    var path = pricePath(t, opts.big ? 150 : 70);
    var vals = path.pts.concat([t.initial_stop, t.initial_target, t.avg_entry_price]).filter(function (v) { return v != null; });
    var lo = Math.min.apply(null, vals), hi = Math.max.apply(null, vals);
    var span = (hi - lo) || 1;
    lo -= span * 0.1; hi += span * 0.1; span = hi - lo;
    var x = function (i) { return P + (i / (path.pts.length - 1)) * (W - P * 2 - (opts.big ? 46 : 0)); };
    var y = function (v) { return H - P - ((v - lo) / span) * (H - P * 2); };
    var line = path.pts.map(function (v, i) { return (i ? "L" : "M") + x(i).toFixed(1) + " " + y(v).toFixed(1); }).join(" ");

    function ref(v, colour, dash, label) {
      if (v == null) return "";
      return '<line x1="' + x(0) + '" x2="' + x(path.pts.length - 1) + '" y1="' + y(v).toFixed(1) +
        '" y2="' + y(v).toFixed(1) + '" stroke="' + colour + '" stroke-width="1"' +
        (dash ? ' stroke-dasharray="' + dash + '"' : "") + ' opacity="' + (opts.big ? 0.85 : 0.6) + '"/>' +
        (opts.big && label
          ? '<text class="axis-label" x="' + (x(path.pts.length - 1) + 6) + '" y="' + (y(v) + 3).toFixed(1) +
            '" fill="' + colour + '">' + esc(label) + "</text>"
          : "");
    }

    var band = '<rect x="' + x(path.entryIdx).toFixed(1) + '" y="' + P + '" width="' +
      Math.max(1, x(path.exitIdx) - x(path.entryIdx)).toFixed(1) + '" height="' + (H - P * 2) +
      '" fill="var(--accent)" opacity="0.06"/>';

    var marks =
      '<circle cx="' + x(path.entryIdx).toFixed(1) + '" cy="' + y(path.pts[path.entryIdx]).toFixed(1) +
        '" r="' + (opts.big ? 5 : 3.4) + '" fill="var(--accent)" stroke="var(--card)" stroke-width="2"/>' +
      '<circle cx="' + x(path.exitIdx).toFixed(1) + '" cy="' + y(path.pts[path.exitIdx]).toFixed(1) +
        '" r="' + (opts.big ? 5 : 3.4) + '" fill="' + (t.r_multiple >= 0 ? "var(--accent)" : "var(--clay)") +
        '" stroke="var(--card)" stroke-width="2"/>';

    /* Label each excursion on the side away from the entry line, so the text
       never lands on the price path it is annotating. */
    function excursion(idx, label) {
      var px = x(idx), py = y(path.pts[idx]);
      var away = py <= y(t.avg_entry_price) ? -9 : 16;
      return '<circle cx="' + px.toFixed(1) + '" cy="' + py.toFixed(1) +
        '" r="3.5" fill="none" stroke="var(--ink-3)" stroke-width="1.5"/>' +
        '<text class="axis-label" x="' + (px + 8).toFixed(1) + '" y="' + (py + away).toFixed(1) +
        '">' + label + "</text>";
    }
    var excursions = opts.big
      ? excursion(path.mfeIdx, "MFE " + fmtR(t.mfe_r)) + excursion(path.maeIdx, "MAE " + fmtR(t.mae_r))
      : "";

    return '<svg viewBox="0 0 ' + W + " " + H + '" preserveAspectRatio="none" role="img" aria-label="' +
      esc(t.strategy_id + " " + t.side + ", result " + fmtR(t.r_multiple) + ", " + outcomeWord(t.r_multiple)) +
      '">' + band +
      ref(t.initial_stop, "var(--clay)", "3 3", "Stop " + fmtPx(t.initial_stop)) +
      ref(t.initial_target, "var(--ink-3)", "3 3", "Target " + fmtPx(t.initial_target)) +
      ref(t.avg_entry_price, "var(--ink-3)", "", "Entry " + fmtPx(t.avg_entry_price)) +
      '<path class="series-line" d="' + line + '"/>' + marks + excursions + "</svg>";
  }

  /* Single-series cumulative-R curve with crosshair + tooltip. */
  function equityCurve(list, opts) {
    opts = opts || {};
    var W = 720, H = opts.h || 190, L = 40, R = 16, T = 14, B = 26;
    var run = 0, pts = list.map(function (s) {
      run += m(s).total_r || 0;
      return { date: s.date, v: run, session: s };
    });
    if (!pts.length) return '<p class="muted small">No sessions in this period.</p>';
    var lo = Math.min(0, Math.min.apply(null, pts.map(function (p) { return p.v; })));
    var hi = Math.max(0.5, Math.max.apply(null, pts.map(function (p) { return p.v; })));
    var span = (hi - lo) || 1;
    lo -= span * 0.12; hi += span * 0.12; span = hi - lo;
    var x = function (i) { return L + (pts.length === 1 ? 0.5 : i / (pts.length - 1)) * (W - L - R); };
    var y = function (v) { return T + (1 - (v - lo) / span) * (H - T - B); };

    var line = pts.map(function (p, i) { return (i ? "L" : "M") + x(i).toFixed(1) + " " + y(p.v).toFixed(1); }).join(" ");
    var area = line + " L" + x(pts.length - 1).toFixed(1) + " " + y(Math.max(lo, 0)).toFixed(1) +
      " L" + x(0).toFixed(1) + " " + y(Math.max(lo, 0)).toFixed(1) + " Z";

    var ticks = "";
    [hi - span * 0.12, (hi + lo) / 2, lo + span * 0.12].forEach(function (v) {
      ticks += '<line class="grid-line" x1="' + L + '" x2="' + (W - R) + '" y1="' + y(v).toFixed(1) +
        '" y2="' + y(v).toFixed(1) + '"/><text class="axis-label" x="6" y="' + (y(v) + 3).toFixed(1) + '">' +
        fmtR(v, 1) + "</text>";
    });
    var zero = (lo < 0 && hi > 0)
      ? '<line class="zero-line" x1="' + L + '" x2="' + (W - R) + '" y1="' + y(0).toFixed(1) +
        '" y2="' + y(0).toFixed(1) + '" stroke-dasharray="2 3"/>' : "";

    var labels = '<text class="axis-label" x="' + L + '" y="' + (H - 8) + '">' + esc(shortDate(pts[0].date)) +
      '</text><text class="axis-label" x="' + (W - R) + '" y="' + (H - 8) + '" text-anchor="end">' +
      esc(shortDate(pts[pts.length - 1].date)) + "</text>";

    var hot = pts.map(function (p, i) {
      return '<rect class="hot" x="' + (x(i) - (W - L - R) / (2 * Math.max(1, pts.length - 1))).toFixed(1) +
        '" y="' + T + '" width="' + ((W - L - R) / Math.max(1, pts.length - 1)).toFixed(1) + '" height="' +
        (H - T - B) + '" fill="transparent" data-cx="' + x(i).toFixed(1) + '" data-cy="' + y(p.v).toFixed(1) +
        '" data-label="' + esc(shortDate(p.date) + " · " + fmtR(p.v) + " cumulative") + '"/>';
    }).join("");

    return '<figure class="chart-wrap" data-chart="equity">' +
      '<svg viewBox="0 0 ' + W + " " + H + '" role="img" aria-label="Cumulative R, ' +
        esc(shortDate(pts[0].date)) + " to " + esc(shortDate(pts[pts.length - 1].date)) + ', ending ' +
        fmtR(pts[pts.length - 1].v) + '">' + ticks + zero +
      '<path class="series-area" d="' + area + '"/><path class="series-line" d="' + line + '"/>' +
      '<circle class="series-end" cx="' + x(pts.length - 1).toFixed(1) + '" cy="' +
        y(pts[pts.length - 1].v).toFixed(1) + '" r="4.5"/>' +
      '<line class="cross" x1="0" x2="0" y1="' + T + '" y2="' + (H - B) +
        '" stroke="var(--rule-2)" stroke-width="1" opacity="0"/>' + labels + hot + "</svg>" +
      '<div class="tooltip"></div>' +
      '<figcaption class="chart-cap">Cumulative R across the period. Ends at <span class="num ' +
        cls(pts[pts.length - 1].v) + '">' + fmtR(pts[pts.length - 1].v) + "</span>.</figcaption></figure>";
  }

  /* Per-session R bars. Diverging by polarity: accent above zero, clay below,
     with a neutral zero rule; the sign in the tooltip carries the meaning too. */
  function dailyBars(list, opts) {
    opts = opts || {};
    var W = 720, H = opts.h || 130, L = 34, R = 10, T = 10, B = 22;
    if (!list.length) return "";
    var vals = list.map(function (s) { return m(s).total_r || 0; });
    var hi = Math.max(1, Math.max.apply(null, vals)), lo = Math.min(-1, Math.min.apply(null, vals));
    var span = hi - lo;
    var y0 = T + (hi / span) * (H - T - B);
    var bw = (W - L - R) / list.length;
    var bars = list.map(function (s, i) {
      var v = m(s).total_r || 0;
      var h = Math.abs(v / span) * (H - T - B);
      var xx = L + i * bw + bw * 0.18, w = bw * 0.64;
      var yy = v >= 0 ? y0 - h : y0;
      var lbl = shortDate(s.date) + " · " + fmtR(v) + " · " + outcomeWord(v);
      return '<rect class="' + (v >= 0 ? "bar-pos" : "bar-neg") + '" x="' + xx.toFixed(1) + '" y="' +
        yy.toFixed(1) + '" width="' + w.toFixed(1) + '" height="' + Math.max(1.5, h).toFixed(1) +
        '" rx="2" data-cx="' + (xx + w / 2).toFixed(1) + '" data-cy="' + yy.toFixed(1) +
        '" data-label="' + esc(lbl) + '"/>';
    }).join("");
    return '<figure class="chart-wrap" data-chart="bars">' +
      '<svg viewBox="0 0 ' + W + " " + H + '" role="img" aria-label="R by session">' +
      '<text class="axis-label" x="4" y="' + (T + 6) + '">' + fmtR(hi, 1) + "</text>" +
      '<text class="axis-label" x="4" y="' + (H - B + 4) + '">' + fmtR(lo, 1) + "</text>" +
      '<line class="zero-line" x1="' + L + '" x2="' + (W - R) + '" y1="' + y0.toFixed(1) +
        '" y2="' + y0.toFixed(1) + '"/>' + bars + "</svg><div class=\"tooltip\"></div>" +
      '<figcaption class="chart-cap">R by session. Bars above the rule are gains, below are losses; ' +
      'every value is signed.</figcaption></figure>';
  }

  function hbars(rows, opts) {
    opts = opts || {};
    var max = Math.max.apply(null, rows.map(function (r) { return Math.abs(r.value); }).concat([0.0001]));
    return '<div class="stack-sm">' + rows.map(function (r) {
      var w = (Math.abs(r.value) / max) * 100;
      return '<div class="hbar"><span class="lbl">' + esc(r.label) + "</span>" +
        '<span class="track"><span class="fill' + (r.warm ? " warm" : "") + '" style="width:' +
        w.toFixed(1) + '%"></span></span><span class="val ' + (opts.plain ? "" : cls(r.value)) + '">' +
        (r.display != null ? r.display : fmtNum(r.value, 1)) + "</span></div>";
    }).join("") + "</div>";
  }

  /* ------------------------------------------------------------------ shared blocks */
  function tradeCard(t, opts) {
    opts = opts || {};
    var mech = t.mechanical_r;
    var delta = deltaR(t.r_multiple, mech);
    return '<a class="trade-card" href="#/trade/' + t.trade_uid + '">' +
      '<div class="trade-chart">' + tradeChart(t) + "</div>" +
      '<div class="trade-main">' +
        '<div class="trade-title"><h3>' + esc(t.strategy_id.replace(/_/g, " ")) + " " +
          esc(t.side) + "</h3>" +
          '<span class="chip chip-ghost">' + esc(t.symbol) + "</span>" +
          '<span class="chip chip-ghost">' + esc(t.execution_mode.replace("_", "-")) + "</span>" +
          '<span style="margin-left:auto;white-space:nowrap">' +
            '<span class="num ' + cls(t.r_multiple) + '" style="font-size:19px">' + fmtR(t.r_multiple) + "</span> " +
            '<span class="muted small">' + outcomeWord(t.r_multiple) + "</span></span></div>" +
        '<div class="kv">' +
          '<div><span class="k">Entry</span><span class="v">' + etTime(t.entry_at) + " · " + fmtPx(t.avg_entry_price) + "</span></div>" +
          '<div><span class="k">Exit</span><span class="v">' + etTime(t.exit_at) + " · " + fmtPx(t.avg_exit_price) + "</span></div>" +
          '<div><span class="k">MFE / MAE</span><span class="v">' + fmtR(t.mfe_r, 1) + " / " + fmtR(t.mae_r, 1) + "</span></div>" +
          '<div><span class="k">Held</span><span class="v">' + fmtDur(t.holding_seconds) + "</span></div>" +
          '<div><span class="k">Mechanical</span><span class="v">' + fmtR(mech) + "</span></div>" +
          '<div><span class="k">vs mechanical</span><span class="v ' + cls(delta) + '">' + fmtR(delta) + "</span></div>" +
        "</div>" +
        '<div class="row">' + tagChips(t.tags) + "</div>" +
        (t.execution_note ? '<p class="trade-note">' + esc(t.execution_note) + "</p>" : "") +
      "</div></a>";
  }

  function oppRow(o) {
    return '<div class="rating"><span class="lbl">' +
      '<span class="num muted" style="font-size:12px">' + etTime(o.qualified_at) + "</span> &nbsp;" +
      esc(o.strategy_id.replace(/_/g, " ")) + " " + esc(o.direction) +
      (o.status_reason ? '<br><span class="muted small">' + esc(o.status_reason) + "</span>" : "") +
      "</span>" +
      '<span class="row" style="gap:10px">' + oppChip(o.status) +
      '<span class="num muted" style="font-size:12.5px" title="Mechanical reference result">' +
      fmtR(o.mechanical_r) + "</span></span></div>";
  }

  function provenance(kind, meta) {
    return '<div class="prov"><span>' + esc(kind) + "</span>" +
      Object.keys(meta).map(function (k) { return "<span><b>" + esc(k) + "</b> " + esc(meta[k]) + "</span>"; }).join("") +
      "</div>";
  }

  /* ------------------------------------------------------------------ view: TODAY */
  var dayState = "after";

  function viewToday() {
    var s = BY_DATE[TODAY] || SESSIONS[SESSIONS.length - 1];
    var cut = dayState === "pre" ? "09:29" : dayState === "mid" ? "11:30" : "23:59";
    var trades = s.trades.filter(function (t) { return etTime(t.entry_at) <= cut; });
    var opps = s.opportunities.filter(function (o) { return etTime(o.qualified_at) <= cut; });
    var mm = m(s);
    var live = trades.reduce(function (a, t) { return a + (t.r_multiple || 0); }, 0);
    var liveNet = trades.reduce(function (a, t) { return a + (t.net_pnl || 0); }, 0);
    var riskUsed = trades.reduce(function (a, t) { return a + Math.max(0, -(t.r_multiple || 0)); }, 0);
    var limit = s.planned_max_risk_r || 2;

    var head = '<div class="page-head"><div class="grow">' +
      '<span class="eyebrow">' + esc(longDate(s.date)) + " · session " + esc(s.session_uid) + "</span>" +
      "<h1>Today</h1>" +
      '<p class="page-sub">' +
        (dayState === "pre" ? "Checked in. Market opens in 18 minutes."
          : dayState === "mid" ? "Session in progress."
          : "Session closed. Check-out submitted at " + etTime(s.post ? s.post.submitted_at : null) + ".") +
      "</p></div>" +
      '<div class="daystate" role="group" aria-label="View the day at a point in time">' +
        ["pre", "mid", "after"].map(function (k) {
          return '<button data-daystate="' + k + '" aria-pressed="' + (dayState === k) + '">' +
            { pre: "Before open", mid: "Mid-session", after: "After close" }[k] + "</button>";
        }).join("") +
      "</div></div>";

    /* --- the morning card is the same object in all three states, it just
           stops being the headline once the session starts --- */
    var pre = s.pre || {};
    var checkin = '<section class="card"><div class="card-head"><span class="eyebrow">Morning check-in</span>' +
      '<span class="muted small num">' + (pre.fill_seconds || 0) + "s to complete</span></div>" +
      '<div class="grid g-fit" style="gap:22px"><div class="stack-sm">' +
        rating("Energy", pre.energy) + rating("Focus", pre.focus) +
        rating("Stress", pre.stress, true) + rating("Desire to trade", pre.desire_to_trade) +
      '</div><div class="stack-sm">' +
        '<div class="rating"><span class="lbl">Sleep</span><span class="num">' + fmtNum(pre.sleep_hours, 1) + " h</span></div>" +
        '<div class="rating"><span class="lbl">Bias</span><span class="num">' + esc(pre.bias || "—") + "</span></div>" +
        '<div class="rating"><span class="lbl">Planned risk</span><span class="num">' + fmtNum(limit, 1) + "R max</span></div>" +
        '<div class="rating"><span class="lbl">Daily loss limit</span><span class="num">$' + fmtNum(s.daily_loss_limit, 0) + "</span></div>" +
      "</div></div>" +
      '<div class="reflect" style="margin-top:16px"><div class="reflect-item">' +
        '<span class="k">A well-traded day today means</span>' +
        '<span class="t">' + esc(pre.well_traded_definition || "—") + "</span></div>" +
        (pre.note ? '<div class="reflect-item"><span class="k">Note</span><span class="t">' + esc(pre.note) + "</span></div>" : "") +
      "</div></section>";

    var statBlock;
    if (dayState === "pre") {
      statBlock = '<div class="stats stats-4">' +
        stat("Session", "Planned", "opens 09:30 ET", "sm") +
        stat("Risk budget", fmtNum(limit, 1) + "R", "not yet used", "sm") +
        stat("Strategies", "2", "10AM Model, DORB", "sm") +
        stat("Trades", "0", "before the open", "sm") + "</div>";
    } else {
      statBlock = '<div class="stats stats-4">' +
        stat("Net P&L", fmtMoney(liveNet), (dayState === "mid" ? "so far · " : "") + outcomeWord(liveNet), cls(liveNet)) +
        stat("R", fmtR(live), trades.length + (trades.length === 1 ? " trade" : " trades")) +
        stat("Risk used", fmtNum(riskUsed, 1) + "R", "of " + fmtNum(limit, 1) + "R planned", "sm") +
        stat("Qualified setups", String(opps.length),
             opps.filter(function (o) { return o.status === "MISSED"; }).length + " missed", "sm") + "</div>";
    }

    var left = "", right = "";

    if (dayState === "pre") {
      left = checkin + planCard(s);
      right = marketCard(s, true) + remindersCard(dayState);
    } else if (dayState === "mid") {
      left = '<section class="card"><div class="card-head"><span class="eyebrow">Trades so far</span>' +
        '<a class="crumb" href="#/session/' + s.date + '">full session review →</a></div>' +
        (trades.length ? '<div class="stack">' + trades.map(function (t) { return tradeCard(t); }).join("") + "</div>"
                       : '<p class="muted">No trades yet.</p>') + "</section>" +
        oppCard(opps);
      right = riskCard(riskUsed, limit, s) + checkin;
    } else {
      left = '<section class="card"><div class="card-head"><span class="eyebrow">Trades</span>' +
        '<a class="crumb" href="#/session/' + s.date + '">full session review →</a></div>' +
        (trades.length ? '<div class="stack">' + trades.map(function (t) { return tradeCard(t); }).join("") + "</div>"
                       : '<p class="muted">No trades taken.</p>') + "</section>" +
        oppCard(opps) + reflectionCard(s);
      right = '<section class="card"><div class="card-head"><span class="eyebrow">How the day scored</span></div>' +
        dial(mm.process_score) +
        '<p class="small muted" style="margin-top:12px">Process score contains no P&amp;L term. ' +
        "It is rule adherence, execution, patience, emotional control and plan conformance.</p>" +
        '<hr class="divider" style="margin:16px 0">' +
        '<div class="stack-sm">' +
          rating("Execution quality", (s.post || {}).execution_quality) +
          rating("Rule adherence", (s.post || {}).rule_adherence) +
          rating("Patience", (s.post || {}).patience) +
          rating("Emotional control", (s.post || {}).emotional_control) +
        "</div></section>" + narrativeCard(s) + checkin;
    }

    return head + statBlock + '<div class="grid g-main" style="margin-top:22px">' +
      '<div class="stack">' + left + '</div><div class="stack">' + right + "</div></div>";
  }

  function planCard(s) {
    var strat = {};
    s.opportunities.forEach(function (o) { strat[o.strategy_id] = true; });
    return '<section class="card"><div class="card-head"><span class="eyebrow">Session plan</span></div>' +
      '<div class="kv" style="grid-template-columns:repeat(auto-fit,minmax(120px,1fr))">' +
      '<div><span class="k">Account</span><span class="v">Eval 50k</span></div>' +
      '<div><span class="k">Mode</span><span class="v">' + esc(s.mode) + "</span></div>" +
      '<div><span class="k">Max risk</span><span class="v">' + fmtNum(s.planned_max_risk_r, 1) + "R</span></div>" +
      '<div><span class="k">Loss limit</span><span class="v">$' + fmtNum(s.daily_loss_limit, 0) + "</span></div>" +
      "</div><hr class=\"divider\" style=\"margin:16px 0\">" +
      '<span class="eyebrow">Planned strategies</span><div class="row">' +
      Object.keys(strat).map(function (k) { return '<span class="chip chip-accent">' + esc(k.replace(/_/g, " ")) + "</span>"; }).join("") +
      "</div></section>";
  }

  function riskCard(used, limit, s) {
    var pct = Math.min(100, (used / limit) * 100);
    return '<section class="card"><div class="card-head"><span class="eyebrow">Risk against plan</span></div>' +
      '<div class="hbar"><span class="lbl">Risk used</span><span class="track">' +
      '<span class="fill' + (pct > 75 ? " warm" : "") + '" style="width:' + pct.toFixed(0) + '%"></span></span>' +
      '<span class="val">' + fmtNum(used, 1) + "R</span></div>" +
      '<p class="small muted" style="margin-top:10px">' + fmtNum(limit - used, 1) +
      "R of the planned budget remains. Daily loss limit $" + fmtNum(s.daily_loss_limit, 0) +
      " is enforced by the platform, not by this journal.</p></section>";
  }

  function oppCard(opps) {
    var missed = opps.filter(function (o) { return o.status === "MISSED"; });
    return '<section class="card"><div class="card-head"><span class="eyebrow">Qualified setups</span>' +
      '<span class="muted small">' + opps.length + " qualified · " + missed.length + " missed</span></div>" +
      (opps.length ? '<div class="stack-sm">' + opps.map(oppRow).join("") + "</div>"
                   : '<p class="muted">No setup qualified today.</p>') +
      '<p class="small muted" style="margin-top:12px">Every qualified setup is logged whether or not ' +
      "it was traded. The number on the right is what the mechanical rules would have produced.</p></section>";
  }

  function reflectionCard(s) {
    var p = s.post || {};
    var flags = [
      ["overtraded", "Overtraded"], ["revenge_trade", "Revenge trade"], ["stop_moved", "Stop moved"],
      ["oversized", "Oversized"], ["missed_qualified", "Missed a qualified setup"],
      ["manual_override", "Manual override"]
    ].filter(function (f) { return p[f[0]]; });
    return '<section class="card"><div class="card-head"><span class="eyebrow">Reflection</span>' +
      '<span class="chip ' + (p.well_traded === "yes" ? "chip-accent" : p.well_traded === "no" ? "chip-flag" : "chip-watch") +
      '">well traded: ' + esc(p.well_traded || "—") + "</span></div>" +
      '<div class="reflect">' +
      (p.best_decision ? '<div class="reflect-item"><span class="k">Best decision</span><span class="t">' + esc(p.best_decision) + "</span></div>" : "") +
      (p.biggest_mistake ? '<div class="reflect-item flag"><span class="k">Biggest mistake</span><span class="t">' + esc(p.biggest_mistake) + "</span></div>" : "") +
      (p.unusual_context ? '<div class="reflect-item"><span class="k">Unusual context</span><span class="t">' + esc(p.unusual_context) + "</span></div>" : "") +
      "</div>" +
      (flags.length ? '<div class="row" style="margin-top:14px">' + flags.map(function (f) {
        return '<span class="chip chip-flag">' + esc(f[1]) + "</span>"; }).join("") + "</div>" : "") +
      provenance("Written by you", { submitted: etTime(p.submitted_at) + " ET", took: (p.fill_seconds || 0) + "s" }) +
      "</section>";
  }

  function narrativeCard(s) {
    if (!s.narrative || !s.narrative.length) return "";
    var n = s.narrative[0];
    return '<section class="card"><div class="card-head"><span class="eyebrow">Daily summary</span>' +
      '<span class="chip chip-ghost">generated</span></div>' +
      '<div class="prose">' + n.text.split("\n\n").map(function (p) { return "<p>" + esc(p) + "</p>"; }).join('<p style="height:8px"></p>') + "</div>" +
      provenance("Generated summary — facts from the session record, not a rewrite of your words",
        { model: n.model, version: n.model_version, at: etTime(n.created_at) + " ET" }) + "</section>";
  }

  function marketCard(s, compact) {
    if (!s.market || !s.market.length) return "";
    var c = s.market[0];
    var ev = [];
    try { ev = JSON.parse(c.econ_events || "[]"); } catch (e) { ev = []; }
    var body = '<div class="kv" style="grid-template-columns:repeat(auto-fit,minmax(96px,1fr))">' +
      '<div><span class="k">Prior close</span><span class="v">' + fmtPx(c.prior_close) + "</span></div>" +
      '<div><span class="k">Gap</span><span class="v">' + (c.gap_points > 0 ? "+" : c.gap_points < 0 ? MINUS : "") + Math.abs(c.gap_points).toFixed(2) + "</span></div>" +
      '<div><span class="k">ATR(14)</span><span class="v">' + fmtNum(c.atr14, 1) + "</span></div>" +
      '<div><span class="k">Trend state</span><span class="v">' + esc(c.trend_state) + "</span></div>" +
      '<div><span class="k">O/N high</span><span class="v">' + fmtPx(c.overnight_high) + "</span></div>" +
      '<div><span class="k">O/N low</span><span class="v">' + fmtPx(c.overnight_low) + "</span></div>" +
      (compact ? "" :
      '<div><span class="k">Opening range</span><span class="v">' + fmtPx(c.opening_range_low) + "–" + fmtPx(c.opening_range_high) + "</span></div>" +
      '<div><span class="k">Session range</span><span class="v">' + fmtNum(c.session_range, 2) + "</span></div>") +
      "</div>" +
      (ev.length ? '<div class="row" style="margin-top:12px">' + ev.map(function (e) {
        return '<span class="chip chip-watch">' + esc(e.time + " " + e.name) + "</span>"; }).join("") + "</div>" : "");
    return '<section class="card"><div class="card-head"><span class="eyebrow">Market context</span>' +
      '<span class="muted small">measured, not felt</span></div>' + body +
      '<p class="small muted" style="margin-top:12px">These are objective values from the data feed. ' +
      'How the session <em>felt</em> lives in your notes, never here.</p></section>';
  }

  function remindersCard() {
    return '<section class="card"><div class="card-head"><span class="eyebrow">Today\'s prompts</span></div>' +
      '<div class="stack-sm">' +
      '<div class="rating"><span class="lbl">Pre-session check-in</span><span class="chip chip-accent">done 09:12</span></div>' +
      '<div class="rating"><span class="lbl">Post-session check-out</span><span class="chip chip-ghost">16:05 ET</span></div>' +
      '<div class="rating"><span class="lbl">Weekly review</span><span class="chip chip-ghost">Friday 16:30 ET</span></div>' +
      "</div><p class=\"small muted\" style=\"margin-top:12px\">Prompts are sent by a scheduled job on your machine, " +
      "not by an assistant that has to be running. See <a href=\"#/capture\">Capture</a>.</p></section>";
  }

  /* ------------------------------------------------------------------ view: SESSION */
  function viewSession(dateKey) {
    var s = BY_DATE[dateKey];
    if (!s) return '<div class="card">Session not found.</div>';
    var mm = m(s);
    var idx = SESSIONS.indexOf(s);
    var prev = SESSIONS[idx - 1], next = SESSIONS[idx + 1];

    var items = [];
    if (s.pre) items.push({ t: s.pre.submitted_at, kind: "checkin", title: "Pre-session check-in",
      meta: "energy " + s.pre.energy + "/5 · focus " + s.pre.focus + "/5 · stress " + s.pre.stress + "/5",
      detail: esc(s.pre.well_traded_definition || "") });
    s.events.forEach(function (e) {
      // check-ins and qualified-setup notices are already rendered from their
      // own records; the event log would duplicate them.
      if (/check-in|check-out|qualified/i.test(e.message)) return;
      items.push({ t: e.occurred_at, kind: e.level === "warn" ? "missed" : "event",
        title: e.message, meta: e.source });
    });
    s.opportunities.forEach(function (o) {
      if (o.status === "TAKEN" || o.status === "BOT_EXECUTED") return;
      items.push({ t: o.qualified_at, kind: o.status === "MISSED" ? "missed" : "event",
        title: o.strategy_id.replace(/_/g, " ") + " " + o.direction + " — " + (OPP_WORDS[o.status] || [o.status])[0],
        meta: "mechanical " + fmtR(o.mechanical_r),
        detail: esc(o.status_reason || "") });
    });
    s.trades.forEach(function (t) {
      items.push({ t: t.entry_at, kind: "trade",
        title: "Entry — " + t.strategy_id.replace(/_/g, " ") + " " + t.side + " ×" + t.quantity,
        meta: fmtPx(t.avg_entry_price) + " · stop " + fmtPx(t.initial_stop),
        detail: esc(t.execution_note || ""), href: "#/trade/" + t.trade_uid });
      items.push({ t: t.exit_at, kind: t.tags.length ? "flag" : "trade",
        title: "Exit — " + fmtR(t.r_multiple) + " " + outcomeWord(t.r_multiple),
        meta: t.exit_reason + " · held " + fmtDur(t.holding_seconds),
        detail: t.tags.length ? "Flagged: " + t.tags.map(tagLabel).join(", ") : "",
        href: "#/trade/" + t.trade_uid });
    });
    if (s.post) items.push({ t: s.post.submitted_at, kind: "checkin", title: "Post-session check-out",
      meta: "well traded: " + (s.post.well_traded || "—"),
      detail: esc(s.post.biggest_mistake || "") });
    items.sort(function (a, b) { return a.t < b.t ? -1 : 1; });

    var timeline = '<ul class="timeline">' + items.map(function (it, i) {
      var hasDetail = !!it.detail;
      return '<li class="tl-item" data-kind="' + it.kind + '">' +
        '<span class="tl-time">' + etTime(it.t) + '</span><span class="tl-dot"><i></i></span>' +
        '<div class="tl-body">' +
        (hasDetail
          ? '<button class="tl-toggle" data-tl="' + i + '" aria-expanded="false"><span class="tl-head">' +
            '<span class="tl-title">' + esc(it.title) + '</span><span class="tl-meta">' + esc(it.meta) + "</span></span></button>" +
            '<div class="tl-detail" id="tl-' + i + '" hidden>' + it.detail +
            (it.href ? ' <a class="crumb" href="' + it.href + '">open trade →</a>' : "") + "</div>"
          : '<span class="tl-head"><span class="tl-title">' + esc(it.title) + '</span>' +
            '<span class="tl-meta">' + esc(it.meta) + "</span></span>") +
        "</div></li>";
    }).join("") + "</ul>";

    var post = s.post || {}, pre = s.pre || {};

    return '<div class="page-head"><div class="grow">' +
      '<a class="crumb" href="#/calendar">← calendar</a>' +
      '<h1 style="margin-top:8px">' + esc(longDate(s.date)) + "</h1>" +
      '<p class="page-sub">' + esc(s.session_uid) + " · " + esc(s.mode) + " · " + esc(s.tz) + "</p></div>" +
      '<div class="row">' +
        (prev ? '<a class="btn" href="#/session/' + prev.date + '">← ' + esc(shortDate(prev.date)) + "</a>" : "") +
        (next ? '<a class="btn" href="#/session/' + next.date + '">' + esc(shortDate(next.date)) + " →</a>" : "") +
      "</div></div>" +

      '<section class="card" style="padding:0;overflow:hidden">' +
      '<div class="stats stats-4">' +
        stat("Net P&L", fmtMoney(mm.net_pnl), outcomeWord(mm.net_pnl), cls(mm.net_pnl)) +
        stat("R", fmtR(mm.total_r), (mm.trade_count || 0) + " trades · " + (mm.win_count || 0) + " winners") +
        stat("Process score", fmtNum(mm.process_score, 0), "no P&L in this number", "sm") +
        stat("Rule adherence", (mm.rule_adherence || "—") + "/5",
             (mm.mistake_count || 0) + (mm.mistake_count === 1 ? " flag" : " flags"), "sm") +
      "</div>" +
      '<div class="stats stats-3" style="border-top:1px solid var(--rule);border-radius:0">' +
        stat("Qualified setups", String(mm.opportunities_total || 0),
             (mm.opportunities_taken || 0) + " taken · " + (mm.opportunities_missed || 0) + " missed", "sm") +
        stat("Mechanical reference", fmtR(mm.mechanical_r), "what the rules alone produced", "sm") +
        stat("Your difference", fmtR(mm.user_value_added_r),
             (mm.user_value_added_r >= 0 ? "discretion added" : "discretion cost"), "sm " + cls(mm.user_value_added_r)) +
      "</div></section>" +

      (s.narrative && s.narrative.length ? '<div style="margin-top:22px">' + narrativeCard(s) + "</div>" : "") +

      '<div class="grid g-main" style="margin-top:22px"><div class="stack">' +
        '<section class="card"><div class="card-head"><span class="eyebrow">Timeline</span>' +
        '<span class="muted small">click an entry to expand</span></div>' + timeline + "</section>" +
        '<section class="card card-quiet" style="padding:0;border:0">' +
        '<div class="card-head"><span class="eyebrow">Trades</span></div>' +
        (s.trades.length ? '<div class="stack">' + s.trades.map(function (t) { return tradeCard(t); }).join("") + "</div>"
                         : '<p class="muted">No trades taken this session.</p>') + "</section>" +
        oppCard(s.opportunities) +
      "</div><div class=\"stack\">" +
        '<section class="card"><div class="card-head"><span class="eyebrow">How I traded</span></div>' +
        dial(mm.process_score) +
        '<hr class="divider" style="margin:16px 0">' +
        '<span class="eyebrow">Before the open</span><div class="stack-sm" style="margin-bottom:14px">' +
          rating("Energy", pre.energy) + rating("Focus", pre.focus) + rating("Stress", pre.stress, true) +
          '<div class="rating"><span class="lbl">Sleep</span><span class="num">' + fmtNum(pre.sleep_hours, 1) + " h</span></div>" +
        "</div>" +
        '<span class="eyebrow">After the close</span><div class="stack-sm">' +
          rating("Execution quality", post.execution_quality) +
          rating("Rule adherence", post.rule_adherence) +
          rating("Patience", post.patience) +
          rating("Emotional control", post.emotional_control) +
        "</div></section>" +
        reflectionCard(s) +
        voiceCard(s) +
        marketCard(s) +
      "</div></div>";
  }

  function voiceCard(s) {
    if (!s.voice || !s.voice.length) return "";
    var v = s.voice[0];
    return '<section class="card"><div class="card-head"><span class="eyebrow">Voice note</span>' +
      '<span class="muted small num">' + Math.round(v.duration_seconds) + "s</span></div>" +
      '<div class="mic" style="margin-bottom:12px"><span class="dot"></span>' +
      '<span class="t">Recorded at ' + etTime(v.recorded_at) + " ET</span>" +
      '<span class="num">audio kept</span></div>' +
      '<div class="quote">“' + esc(v.transcript) + "”</div>" +
      provenance("Your words, transcribed verbatim",
        { engine: v.transcript_engine, version: v.transcript_version, edited: "never" }) + "</section>";
  }

  /* ------------------------------------------------------------------ view: TRADE */
  function viewTrade(uid) {
    var t = TRADE_BY_UID[uid];
    if (!t) return '<div class="card">Trade not found.</div>';
    var s = t._session, mm = m(s);
    var delta = deltaR(t.r_multiple, t.mechanical_r);
    var mkt = (s.market && s.market[0]) || {};
    var accepted = (t.ai_suggestions || []).filter(function (a) { return a.status === "accepted"; });
    var rejected = (t.ai_suggestions || []).filter(function (a) { return a.status === "rejected"; });

    return '<div class="page-head"><div class="grow">' +
      '<a class="crumb" href="#/session/' + s.date + '">← ' + esc(longDate(s.date)) + "</a>" +
      "<h1 style=\"margin-top:8px\">" + esc(t.strategy_id.replace(/_/g, " ")) + " " + esc(t.side) +
      ' <span class="muted" style="font-size:20px">' + esc(t.symbol) + "</span></h1>" +
      '<p class="page-sub">' + etTime(t.entry_at) + " → " + etTime(t.exit_at) + " ET · " +
      esc(t.execution_mode.replace("_", "-")) + " · " + esc(t.strategy_id) + " v" + esc(t.strategy_version) +
      "</p></div>" +
      '<div class="row"><span class="num ' + cls(t.r_multiple) + '" style="font-size:30px">' +
      fmtR(t.r_multiple) + '</span><span class="muted">' + outcomeWord(t.r_multiple) + "</span></div></div>" +

      '<section class="card"><div class="card-head"><span class="eyebrow">Chart</span>' +
      '<span class="muted small">entry · stop · target · MFE · MAE</span></div>' +
      '<div class="chart-wrap">' + tradeChart(t, { w: 900, h: 330, big: true }) + "</div>" +
      '<p class="chart-cap">Synthetic price path standing in for the captured screenshot set. In production ' +
      'this panel plays the four snapshots below, taken automatically at capture time.</p>' +
      '<div class="row" style="margin-top:10px">' + (t.media || []).map(function (a) {
        return '<span class="chip chip-ghost">' + esc(a.phase.replace("_", " ")) + " · " + esc(a.timeframe) + "</span>";
      }).join("") + "</div></section>" +

      '<div class="stats stats-4" style="margin-top:18px">' +
        stat("R", fmtR(t.r_multiple), outcomeWord(t.r_multiple), cls(t.r_multiple)) +
        stat("Net P&L", fmtMoney(t.net_pnl), "fees " + fmtMoney(-(t.fees || 0)), "sm " + cls(t.net_pnl)) +
        stat("MFE / MAE", fmtR(t.mfe_r, 1) + " / " + fmtR(t.mae_r, 1),
             t.r_captured_pct != null
               ? "kept " + fmtNum(t.r_captured_pct, 0) + "% of the favourable move"
               : "reached " + fmtR(t.mfe_r, 1) + " before the stop", "sm") +
        stat("Held", fmtDur(t.holding_seconds), "to MFE " + fmtDur(t.seconds_to_mfe), "sm") +
      "</div>" +

      '<div class="grid g-main" style="margin-top:22px"><div class="stack">' +
        '<section class="card"><div class="card-head"><span class="eyebrow">Execution</span></div>' +
        '<div class="kv" style="grid-template-columns:repeat(auto-fit,minmax(110px,1fr))">' +
          '<div><span class="k">Entry</span><span class="v">' + fmtPx(t.avg_entry_price) + "</span></div>" +
          '<div><span class="k">Exit</span><span class="v">' + fmtPx(t.avg_exit_price) + "</span></div>" +
          '<div><span class="k">Initial stop</span><span class="v">' + fmtPx(t.initial_stop) + "</span></div>" +
          '<div><span class="k">Target</span><span class="v">' + fmtPx(t.initial_target) + "</span></div>" +
          '<div><span class="k">Quantity</span><span class="v">' + t.quantity + " / " + t.planned_quantity + " planned</span></div>" +
          '<div><span class="k">Size deviation</span><span class="v ' + cls(-Math.abs(t.size_deviation_pct || 0)) + '">' +
            (t.size_deviation_pct ? (t.size_deviation_pct > 0 ? "+" : MINUS) + Math.abs(t.size_deviation_pct) + "%" : "on plan") + "</span></div>" +
          '<div><span class="k">Entry slippage</span><span class="v ' +
            (t.entry_slippage_ticks < 0 ? "v-neg" : "") + '">' + fmtNum(t.entry_slippage_ticks, 2) +
            " ticks<br><span class=\"s\" style=\"font-family:var(--sans)\">" +
            (t.entry_slippage_ticks == null ? "no reference price"
              : t.entry_slippage_ticks < 0 ? "adverse" : t.entry_slippage_ticks > 0 ? "favourable" : "at price") +
            "</span></span></div>" +
          '<div><span class="k">Exit reason</span><span class="v">' + esc(t.exit_reason) + "</span></div>" +
        "</div>" +
        (t.execution_note ? '<p class="trade-note" style="margin-top:14px">' + esc(t.execution_note) + "</p>" : "") +
        '<div class="row" style="margin-top:14px">' + tagChips(t.tags) + "</div></section>" +

        '<section class="card"><div class="card-head"><span class="eyebrow">Against the mechanical reference</span></div>' +
        '<div class="stats stats-3" style="border-radius:var(--r-sm)">' +
          stat("You", fmtR(t.r_multiple), "as executed", "sm " + cls(t.r_multiple)) +
          stat("Rules alone", fmtR(t.mechanical_r), "same signal, no discretion", "sm") +
          stat("Difference", fmtR(delta), deltaWord(delta), "sm " + cls(delta)) +
        "</div>" +
        '<p class="small muted" style="margin-top:12px">The reference is recomputed from the signal and the ' +
        "strategy version in force at the time (" + esc(t.strategy_id) + " v" + esc(t.strategy_version) +
        "). It never changes when the strategy is later edited.</p></section>" +

        '<section class="card"><div class="card-head"><span class="eyebrow">Labels</span></div>' +
        '<span class="eyebrow">Confirmed by you</span><div class="row" style="margin-bottom:16px">' + tagChips(t.tags) + "</div>" +
        (accepted.length || rejected.length
          ? '<span class="eyebrow">Model suggestions</span><div class="stack-sm">' +
            accepted.concat(rejected).map(function (a) {
              return '<div class="rating"><span class="lbl"><b>' + esc(tagLabel(a.tag_code)) + "</b>" +
                '<br><span class="muted small">' + esc(a.content) + "</span></span>" +
                '<span class="row" style="gap:8px"><span class="num muted" style="font-size:12px">' +
                (a.confidence * 100).toFixed(0) + "%</span>" +
                '<span class="chip ' + (a.status === "accepted" ? "chip-accent" : "chip-ghost") + '">' +
                esc(a.status === "accepted" ? "you accepted" : "you rejected") + "</span></span></div>";
            }).join("") + "</div>" +
            '<p class="small muted" style="margin-top:12px">Suggestions never become labels on their own. ' +
            "Only the confirmed row above is used in any statistic.</p>"
          : '<p class="small muted">No model suggestions for this trade.</p>') + "</section>" +
      "</div><div class=\"stack\">" +
        '<section class="card"><div class="card-head"><span class="eyebrow">Market context at entry</span></div>' +
        '<div class="stack-sm">' +
        '<div class="rating"><span class="lbl">Trend state</span><span class="num">' + esc(mkt.trend_state || "—") + "</span></div>" +
        '<div class="rating"><span class="lbl">ATR(14)</span><span class="num">' + fmtNum(mkt.atr14, 1) + "</span></div>" +
        '<div class="rating"><span class="lbl">Opening range</span><span class="num">' +
          fmtPx(mkt.opening_range_low) + "–" + fmtPx(mkt.opening_range_high) + "</span></div>" +
        '<div class="rating"><span class="lbl">Prior close</span><span class="num">' + fmtPx(mkt.prior_close) + "</span></div>" +
        '<div class="rating"><span class="lbl">Session cumulative after</span><span class="num ' +
          cls(t.session_cum_pnl_after) + '">' + fmtMoney(t.session_cum_pnl_after) + "</span></div>" +
        "</div></section>" +
        '<section class="card"><div class="card-head"><span class="eyebrow">Session state</span></div>' +
        '<div class="stack-sm">' +
          rating("Energy that morning", (s.pre || {}).energy) +
          rating("Focus that morning", (s.pre || {}).focus) +
          rating("Stress that morning", (s.pre || {}).stress, true) +
        "</div>" +
        '<p class="small muted" style="margin-top:10px">Shown because you reported it, not because a ' +
        "correlation has been established.</p></section>" +
        researchDetails(t) +
      "</div></div>";
  }

  function researchDetails(t) {
    return '<details class="disclosure card"><summary>Research details</summary>' +
      '<div class="stack-sm">' +
      '<div class="rating"><span class="lbl">Trade UID</span><span class="num small">' + esc(t.trade_uid) + "</span></div>" +
      '<div class="rating"><span class="lbl">Calc version</span><span class="num small">' + esc(D.meta.calc_version) + "</span></div>" +
      '<div class="rating"><span class="lbl">Gross / fees</span><span class="num small">' +
        fmtMoney(t.gross_pnl) + " / " + fmtMoney(-(t.fees || 0)) + "</span></div>" +
      '<div class="rating"><span class="lbl">Seconds to MAE</span><span class="num small">' + (t.seconds_to_mae || 0) + "s</span></div>" +
      '<div class="rating"><span class="lbl">Opportunity status</span><span class="num small">' + esc(t.opportunity_status || "—") + "</span></div>" +
      "</div>" +
      '<div class="warnband" style="margin-top:14px"><span class="g">blinded</span>' +
      "<p>Blinded research features exist for this session but are withheld here by design. " +
      "They are only readable in <a href=\"#/research\">Research Mode</a>, and opening them is logged.</p></div>" +
      "</details>";
  }

  /* ------------------------------------------------------------------ view: CALENDAR */
  var calMonth = null;

  function viewCalendar() {
    var months = monthsDesc();
    if (!calMonth || months.indexOf(calMonth) < 0) calMonth = months[0];
    var parts = calMonth.split("-"), yr = +parts[0], mo = +parts[1];
    var first = new Date(Date.UTC(yr, mo - 1, 1));
    var startDow = first.getUTCDay();
    var days = new Date(Date.UTC(yr, mo, 0)).getUTCDate();
    var list = sessionsIn(calMonth, "iso_month");
    var a = aggregate(list);

    var cells = "";
    for (var i = 0; i < startDow; i++) cells += '<div class="cal-cell empty" aria-hidden="true"></div>';
    for (var d = 1; d <= days; d++) {
      var key = yr + "-" + pad(mo) + "-" + pad(d);
      var s = BY_DATE[key];
      var dow = new Date(Date.UTC(yr, mo - 1, d)).getUTCDay();
      if (!s) {
        cells += '<div class="cal-cell empty"><span class="cal-day">' + d + "</span>" +
          '<span class="cal-tag muted">' + (dow === 0 || dow === 6 ? "Weekend" : "No session") + "</span></div>";
        continue;
      }
      var mm = m(s), marks = [];
      if (mm.mistake_count) marks.push('<span class="mark mark-flag">' + mm.mistake_count + " flag" + (mm.mistake_count > 1 ? "s" : "") + "</span>");
      if (mm.opportunities_missed) marks.push('<span class="mark mark-watch">' + mm.opportunities_missed + " missed</span>");
      if (!mm.mistake_count && mm.process_score >= 80) marks.push('<span class="mark mark-good">good process</span>');
      cells += '<a class="cal-cell linked" href="#/session/' + key + '">' +
        '<span class="cal-day">' + d + " · " + DAYS[dow].slice(0, 3) + "</span>" +
        '<span class="cal-r ' + cls(mm.total_r) + '">' + (mm.trade_count ? fmtR(mm.total_r, 1) : "No trade") + "</span>" +
        '<span class="cal-tag">' + (mm.trade_count ? mm.trade_count + (mm.trade_count === 1 ? " trade" : " trades") : "Stayed out") +
        (mm.process_score != null ? " · process " + fmtNum(mm.process_score, 0) : "") + "</span>" +
        '<span class="cal-marks">' + marks.join("") + "</span></a>";
    }

    return '<div class="page-head"><div class="grow">' +
      '<span class="eyebrow">History</span><h1>' + MONTHS[mo - 1] + " " + yr + "</h1>" +
      '<p class="page-sub">' + a.sessions + " sessions · " + a.trades + " trades · " +
      a.noTrade + (a.noTrade === 1 ? " day" : " days") + " with no trade taken</p></div>" +
      '<div class="row">' + months.map(function (k) {
        var p = k.split("-");
        return '<button class="btn" data-cal="' + k + '"' +
          (k === calMonth ? ' style="border-color:var(--accent);color:var(--accent-2)"' : "") + ">" +
          MONTHS[+p[1] - 1].slice(0, 3) + " " + p[0] + "</button>";
      }).join("") + "</div></div>" +

      '<div class="stats stats-4" style="margin-bottom:20px">' +
        stat("Month R", fmtR(a.r), outcomeWord(a.r), cls(a.r)) +
        stat("Process average", fmtNum(a.avgProcess, 0), "of 100", "sm") +
        stat("Rule flags", String(a.mistakes), "across " + a.sessions + " sessions", "sm") +
        stat("Setups missed", String(a.missed), "of " + a.opps + " qualified", "sm") +
      "</div>" +

      '<section class="card"><div class="cal" style="margin-bottom:8px">' +
      ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map(function (d) {
        return '<div class="cal-dow">' + d + "</div>"; }).join("") + "</div>" +
      '<div class="cal">' + cells + "</div>" +
      '<div class="legend" style="margin-top:16px">' +
      '<span><i style="background:var(--clay)"></i>rule flag — labelled on the day</span>' +
      '<span><i style="background:var(--amber)"></i>qualified setup missed</span>' +
      '<span><i style="background:var(--accent)"></i>clean process, score 80+</span>' +
      '<span class="muted">Every marker is also written out in words; colour is never the only carrier.</span>' +
      "</div></section>";
  }

  /* ------------------------------------------------------------------ view: WEEKLY */
  var weekKey = null;

  function viewWeekly() {
    var weeks = weeksDesc();
    if (!weekKey || weeks.indexOf(weekKey) < 0) weekKey = weeks[0];
    var list = sessionsIn(weekKey, "iso_week");
    var a = aggregate(list);
    var prevList = sessionsIn(weeks[weeks.indexOf(weekKey) + 1] || "", "iso_week");
    var prev = aggregate(prevList);

    var byStrategy = {};
    list.forEach(function (s) {
      s.opportunities.forEach(function (o) {
        var k = o.strategy_id;
        byStrategy[k] = byStrategy[k] || { opps: 0, taken: 0, missed: 0, r: 0, mech: 0 };
        byStrategy[k].opps++;
        if (o.status === "TAKEN" || o.status === "BOT_EXECUTED") byStrategy[k].taken++;
        if (o.status === "MISSED") byStrategy[k].missed++;
        byStrategy[k].mech += o.mechanical_r || 0;
      });
      s.trades.forEach(function (t) {
        byStrategy[t.strategy_id] = byStrategy[t.strategy_id] || { opps: 0, taken: 0, missed: 0, r: 0, mech: 0 };
        byStrategy[t.strategy_id].r += t.r_multiple || 0;
      });
    });

    var mistakes = {};
    list.forEach(function (s) {
      s.trades.forEach(function (t) {
        t.tags.forEach(function (g) { mistakes[g] = (mistakes[g] || 0) + 1; });
      });
      if ((s.post || {}).missed_qualified) mistakes.MISSED_SETUP = (mistakes.MISSED_SETUP || 0) + 1;
    });
    var mistakeRows = Object.keys(mistakes).sort(function (x, y) { return mistakes[y] - mistakes[x]; })
      .map(function (k) { return { label: tagLabel(k), value: mistakes[k], display: String(mistakes[k]), warm: true }; });

    var best = list.slice().sort(function (x, y) { return (m(y).total_r || 0) - (m(x).total_r || 0); })[0];
    var worstProcess = list.slice().filter(function (s) { return m(s).process_score != null; })
      .sort(function (x, y) { return (m(x).process_score || 0) - (m(y).process_score || 0); })[0];

    var focus = [];
    if (a.missed > 0) focus.push("Be at the desk for the " + (a.missed === 1 ? "one setup" : a.missed + " setups") +
      " that qualified while you were away — that is where most of the week's lost R sits.");
    if (mistakes.LATE_ENTRY) focus.push("Late entries appeared " + mistakes.LATE_ENTRY +
      " time" + (mistakes.LATE_ENTRY > 1 ? "s" : "") + ". Set the entry order at signal time rather than after confirming twice.");
    if (mistakes.OVERTRADE) focus.push("Overtrading was flagged on " + mistakes.OVERTRADE +
      " occasion" + (mistakes.OVERTRADE > 1 ? "s" : "") + ". Hold the planned trade cap.");
    if (!focus.length) focus.push("No repeat behaviour stands out this week. Keep the current pre-session routine.");

    return '<div class="page-head"><div class="grow">' +
      '<span class="eyebrow">Weekly review</span><h1>' + esc(weekKey) + "</h1>" +
      '<p class="page-sub">' + (list.length ? esc(longDate(list[0].date)) + " – " + esc(longDate(list[list.length - 1].date)) : "") + "</p></div>" +
      '<div class="row">' + weeks.slice(0, 6).map(function (k) {
        return '<button class="btn" data-week="' + k + '"' +
          (k === weekKey ? ' style="border-color:var(--accent);color:var(--accent-2)"' : "") + ">" + esc(k) + "</button>";
      }).join("") + "</div></div>" +

      '<span class="eyebrow">Performance</span>' +
      '<div class="stats stats-4" style="margin-bottom:20px">' +
        stat("Week R", fmtR(a.r), outcomeWord(a.r), cls(a.r)) +
        stat("Expectancy", fmtR(a.expectancy), "per trade over " + a.trades, "sm") +
        stat("Profit factor", a.pf ? fmtNum(a.pf, 2) : "—", fmtNum(a.winRate, 0) + "% winners", "sm") +
        stat("Max drawdown", fmtR(a.maxDD), "intra-week, session grain", "sm " + cls(a.maxDD)) +
      "</div>" +

      '<div class="grid g-main"><div class="stack">' +
        '<section class="card"><div class="card-head"><span class="eyebrow">Cumulative R</span></div>' +
        equityCurve(list) + "</section>" +
        '<section class="card"><div class="card-head"><span class="eyebrow">By session</span></div>' +
        dailyBars(list) + "</section>" +

        '<section class="card"><div class="card-head"><span class="eyebrow">Strategies</span></div>' +
        '<div class="table-wrap"><table><thead><tr><th>Strategy</th><th class="n">Qual.</th>' +
        '<th class="n">Taken</th><th class="n">Missed</th><th class="n">You</th><th class="n">Rules</th>' +
        '<th class="n">Diff.</th></tr></thead><tbody>' +
        Object.keys(byStrategy).map(function (k) {
          var v = byStrategy[k], d = v.r - v.mech;
          return "<tr><td>" + esc(k.replace(/_/g, " ")) + '</td><td class="n">' + v.opps +
            '</td><td class="n">' + v.taken + '</td><td class="n">' + v.missed +
            '</td><td class="n ' + cls(v.r) + '">' + fmtR(v.r, 1) + '</td><td class="n">' + fmtR(v.mech, 1) +
            '</td><td class="n ' + cls(d) + '">' + fmtR(d, 1) + "</td></tr>";
        }).join("") + "</tbody></table></div></section>" +

        '<section class="card"><div class="card-head"><span class="eyebrow">Manual vs mechanical</span>' +
        '<span class="muted small">the discretion audit</span></div>' +
        '<div class="stats stats-3" style="border-radius:var(--r-sm)">' +
          stat("You", fmtR(a.r), "as executed", "sm " + cls(a.r)) +
          stat("Rules alone", fmtR(a.mech), "all qualified setups", "sm") +
          stat("Difference", fmtR(a.uva), a.uva >= 0 ? "discretion added" : "discretion cost", "sm " + cls(a.uva)) +
        "</div><p class=\"small muted\" style=\"margin-top:12px\">Missed setups count against you here: " +
        "the mechanical column includes every qualified setup, taken or not.</p></section>" +

        '<section class="card"><div class="card-head"><span class="eyebrow">Missed opportunities</span>' +
        '<span class="muted small">' + a.missed + " of " + a.opps + " qualified setups</span></div>" +
        (a.missed
          ? '<div class="stack-sm">' + list.reduce(function (acc, s) {
              s.opportunities.filter(function (o) { return o.status === "MISSED"; }).forEach(function (o) {
                acc.push('<div class="rating"><span class="lbl">' + esc(shortDate(s.date)) + " " + etTime(o.qualified_at) +
                  " · " + esc(o.strategy_id.replace(/_/g, " ")) +
                  '<br><span class="muted small">' + esc(o.status_reason || "") + "</span></span>" +
                  '<span class="num ' + cls(o.mechanical_r) + '">' + fmtR(o.mechanical_r) + "</span></div>");
              });
              return acc;
            }, []).join("") + "</div>"
          : '<p class="muted">No qualified setup went untaken this week.</p>') + "</section>" +
      "</div><div class=\"stack\">" +
        '<span class="eyebrow" style="margin-bottom:-6px">Process</span>' +
        '<section class="card">' + dial(a.avgProcess, "Weekly process average") +
        '<div class="stack-sm" style="margin-top:14px">' +
          '<div class="rating"><span class="lbl">Rule adherence</span><span class="num">' + fmtNum(a.avgAdherence, 1) + "/5</span></div>" +
          '<div class="rating"><span class="lbl">Rule flags</span><span class="num">' + a.mistakes + "</span></div>" +
          '<div class="rating"><span class="lbl">Take rate</span><span class="num">' + fmtNum(a.takeRate, 0) + "%</span></div>" +
          '<div class="rating"><span class="lbl">Sessions with no trade</span><span class="num">' + a.noTrade + "</span></div>" +
          '<div class="rating"><span class="lbl">vs previous week</span><span class="num ' +
            cls(a.avgProcess - (prev.avgProcess || a.avgProcess)) + '">' +
            (prev.avgProcess ? (a.avgProcess >= prev.avgProcess ? "+" : MINUS) +
              Math.abs(a.avgProcess - prev.avgProcess).toFixed(0) : "—") + "</span></div>" +
        "</div></section>" +

        '<section class="card"><div class="card-head"><span class="eyebrow">Mistakes</span></div>' +
        (mistakeRows.length ? hbars(mistakeRows, { plain: true }) : '<p class="muted">None recorded.</p>') +
        "</section>" +

        '<section class="card"><div class="card-head"><span class="eyebrow">Sessions worth revisiting</span></div>' +
        (best ? '<div class="rating"><span class="lbl">Best result<br><span class="muted small">' +
          esc(longDate(best.date)) + '</span></span><a class="num ' + cls(m(best).total_r) +
          '" href="#/session/' + best.date + '">' + fmtR(m(best).total_r) + "</a></div>" : "") +
        (worstProcess ? '<div class="rating"><span class="lbl">Weakest process<br><span class="muted small">' +
          esc(longDate(worstProcess.date)) + '</span></span><a class="num" href="#/session/' + worstProcess.date + '">' +
          fmtNum(m(worstProcess).process_score, 0) + "/100</a></div>" : "") +
        "</section>" +

        '<section class="card"><div class="card-head"><span class="eyebrow">Next week</span></div>' +
        '<div class="reflect">' + focus.map(function (f, i) {
          return '<div class="reflect-item"><span class="k">Focus ' + (i + 1) + '</span><span class="t">' + esc(f) + "</span></div>";
        }).join("") + "</div>" +
        provenance("Generated from the week's record", { model: "journal-narrator", version: "0.2.0" }) +
        "</section>" +
      "</div></div>";
  }

  /* ------------------------------------------------------------------ view: MONTHLY */
  var monthKey = null;

  function viewMonthly() {
    var months = monthsDesc();
    if (!monthKey || months.indexOf(monthKey) < 0) monthKey = months[0];
    var list = sessionsIn(monthKey, "iso_month");
    var a = aggregate(list);
    var weeks = [];
    list.forEach(function (s) { if (weeks.indexOf(s.iso_week) < 0) weeks.push(s.iso_week); });
    var weekAgg = weeks.map(function (w) { return { week: w, a: aggregate(sessionsIn(w, "iso_week")) }; });
    var p = monthKey.split("-");

    var mistakeByWeek = weekAgg.map(function (w) {
      return { label: w.week, value: w.a.mistakes, display: String(w.a.mistakes), warm: true };
    });
    var processByWeek = weekAgg.map(function (w) {
      return { label: w.week, value: w.a.avgProcess || 0, display: fmtNum(w.a.avgProcess, 0) };
    });
    var rByWeek = weekAgg.map(function (w) {
      return { label: w.week, value: w.a.r, display: fmtR(w.a.r, 1), warm: w.a.r < 0 };
    });

    return '<div class="page-head"><div class="grow">' +
      '<span class="eyebrow">Monthly review</span><h1>' + MONTHS[+p[1] - 1] + " " + p[0] + "</h1>" +
      '<p class="page-sub">' + a.sessions + " sessions · " + a.trades + " trades · " +
      weeks.length + " weeks</p></div>" +
      '<div class="row">' + months.map(function (k) {
        var q = k.split("-");
        return '<button class="btn" data-month="' + k + '"' +
          (k === monthKey ? ' style="border-color:var(--accent);color:var(--accent-2)"' : "") + ">" +
          MONTHS[+q[1] - 1].slice(0, 3) + "</button>";
      }).join("") + "</div></div>" +

      '<div class="stats stats-4" style="margin-bottom:20px">' +
        stat("Month R", fmtR(a.r), outcomeWord(a.r), cls(a.r)) +
        stat("Expectancy", fmtR(a.expectancy), "per trade", "sm") +
        stat("Process average", fmtNum(a.avgProcess, 0), "of 100", "sm") +
        stat("Discretion", fmtR(a.uva), a.uva >= 0 ? "added over rules" : "cost against rules", "sm " + cls(a.uva)) +
      "</div>" +

      '<div class="grid g-main"><div class="stack">' +
        '<section class="card"><div class="card-head"><span class="eyebrow">Cumulative R</span>' +
        '<span class="muted small">session grain</span></div>' + equityCurve(list, { h: 210 }) + "</section>" +
        '<section class="card"><div class="card-head"><span class="eyebrow">By session</span></div>' +
        dailyBars(list, { h: 140 }) + "</section>" +
        '<section class="card"><div class="card-head"><span class="eyebrow">Trend by week</span></div>' +
        '<span class="eyebrow">R</span>' + hbars(rByWeek) +
        '<hr class="divider" style="margin:16px 0"><span class="eyebrow">Process score</span>' + hbars(processByWeek, { plain: true }) +
        '<hr class="divider" style="margin:16px 0"><span class="eyebrow">Rule flags</span>' + hbars(mistakeByWeek, { plain: true }) +
        "</section>" +
      "</div><div class=\"stack\">" +
        '<section class="card"><div class="card-head"><span class="eyebrow">Consistency</span></div>' +
        '<div class="stack-sm">' +
        '<div class="rating"><span class="lbl">Sessions traded</span><span class="num">' + (a.sessions - a.noTrade) + " of " + a.sessions + "</span></div>" +
        '<div class="rating"><span class="lbl">Check-ins completed</span><span class="num">' + a.sessions + " of " + a.sessions + "</span></div>" +
        '<div class="rating"><span class="lbl">Take rate</span><span class="num">' + fmtNum(a.takeRate, 0) + "%</span></div>" +
        '<div class="rating"><span class="lbl">Setups missed</span><span class="num">' + a.missed + "</span></div>" +
        '<div class="rating"><span class="lbl">Flags per session</span><span class="num">' + fmtNum(a.mistakes / a.sessions, 2) + "</span></div>" +
        "</div></section>" +
        '<section class="card"><div class="card-head"><span class="eyebrow">Behaviour</span></div>' +
        '<p class="prose" style="font-size:15px">Rule flags fell from ' + (weekAgg[0] ? weekAgg[0].a.mistakes : 0) +
        " in the first week to " + (weekAgg[weekAgg.length - 1] ? weekAgg[weekAgg.length - 1].a.mistakes : 0) +
        " in the last. Process average " +
        (weekAgg.length > 1 && weekAgg[weekAgg.length - 1].a.avgProcess >= weekAgg[0].a.avgProcess ? "rose" : "fell") +
        " over the same span. Sessions with no trade taken: " + a.noTrade + ".</p>" +
        provenance("Generated from the month's record", { model: "journal-narrator", version: "0.2.0" }) + "</section>" +
        '<section class="card"><div class="card-head"><span class="eyebrow">Weeks</span></div>' +
        '<div class="stack-sm">' + weekAgg.map(function (w) {
          return '<div class="rating"><span class="lbl">' + esc(w.week) + '<br><span class="muted small">' +
            w.a.trades + " trades · process " + fmtNum(w.a.avgProcess, 0) + "</span></span>" +
            '<span class="num ' + cls(w.a.r) + '">' + fmtR(w.a.r, 1) + "</span></div>";
        }).join("") + "</div></section>" +
      "</div></div>";
  }

  /* ------------------------------------------------------------------ view: STRATEGIES */
  function viewStrategies() {
    var cards = D.strategies.map(function (sv) {
      var score = D.strategy_scorecard.filter(function (r) { return r.strategy_version_id === sv.id; })[0] || {};
      var trades = TRADES.filter(function (t) {
        return t.strategy_id === sv.strategy_id && t.strategy_version === sv.version;
      });
      var r = trades.reduce(function (x, t) { return x + (t.r_multiple || 0); }, 0);
      var wins = trades.filter(function (t) { return t.r_multiple > 0; }).length;
      var grossW = trades.filter(function (t) { return t.r_multiple > 0; })
        .reduce(function (x, t) { return x + t.r_multiple; }, 0);
      var grossL = trades.filter(function (t) { return t.r_multiple < 0; })
        .reduce(function (x, t) { return x + Math.abs(t.r_multiple); }, 0);
      var tags = {};
      trades.forEach(function (t) { t.tags.forEach(function (g) { tags[g] = (tags[g] || 0) + 1; }); });
      var regime = {};
      trades.forEach(function (t) {
        var k = ((t._session.market || [])[0] || {}).trend_state || "unknown";
        regime[k] = (regime[k] || 0) + 1;
      });
      var run = 0, peak = 0, dd = 0;
      trades.forEach(function (t) { run += t.r_multiple || 0; peak = Math.max(peak, run); dd = Math.min(dd, run - peak); });

      return '<section class="card"><div class="card-head"><div>' +
        '<span class="eyebrow">' + esc(sv.automation_level.replace("_", " ")) + " · " +
        esc(sv.qualification_status) + "</span>" +
        "<h2>" + esc(sv.name) + " <span class=\"num muted\" style=\"font-size:15px\">v" + esc(sv.version) + "</span></h2>" +
        '<p class="small muted">active ' + esc(sv.active_from) + " → " + esc(sv.active_to || "now") +
        " · rule hash <span class=\"num\">" + esc(sv.rule_hash.slice(0, 12)) + "</span></p></div>" +
        (sv.active_to ? '<span class="chip chip-ghost">retired</span>' : '<span class="chip chip-accent">in force</span>') +
        "</div>" +
        '<div class="stats stats-4" style="border-radius:var(--r-sm);margin-bottom:16px">' +
          stat("Trades", String(trades.length), wins + " winners", "sm") +
          stat("Total R", fmtR(r), "expectancy " + fmtR(trades.length ? r / trades.length : null, 2), "sm " + cls(r)) +
          stat("Profit factor", grossL ? fmtNum(grossW / grossL, 2) : "—", "gross " + fmtR(grossW, 1) + " / " + fmtR(-grossL, 1), "sm") +
          stat("Max drawdown", fmtR(dd), "trade grain", "sm " + cls(dd)) +
        "</div>" +
        '<div class="grid g-2" style="gap:22px"><div>' +
        '<span class="eyebrow">Opportunity handling</span><div class="stack-sm">' +
        '<div class="rating"><span class="lbl">Qualified</span><span class="num">' + (score.opportunities || 0) + "</span></div>" +
        '<div class="rating"><span class="lbl">Take rate</span><span class="num">' +
          (score.opportunities ? fmtNum((score.taken / score.opportunities) * 100, 0) + "%" : "—") + "</span></div>" +
        '<div class="rating"><span class="lbl">Miss rate</span><span class="num">' +
          (score.opportunities ? fmtNum((score.missed / score.opportunities) * 100, 0) + "%" : "—") + "</span></div>" +
        '<div class="rating"><span class="lbl">Skipped by rule</span><span class="num">' + (score.skipped_by_rule || 0) + "</span></div>" +
        '<div class="rating"><span class="lbl">Skipped by choice</span><span class="num">' + (score.skipped_discretionary || 0) + "</span></div>" +
        "</div></div><div>" +
        '<span class="eyebrow">You vs the rules</span><div class="stack-sm">' +
        '<div class="rating"><span class="lbl">Your average R</span><span class="num ' + cls(score.actual_avg_r) + '">' +
          fmtR(score.actual_avg_r, 2) + "</span></div>" +
        '<div class="rating"><span class="lbl">Mechanical average R</span><span class="num">' + fmtR(score.mechanical_avg_r, 2) + "</span></div>" +
        '<div class="rating"><span class="lbl">Difference over period</span><span class="num ' + cls(score.user_value_added_r) + '">' +
          fmtR(score.user_value_added_r, 1) + "</span></div>" +
        "</div>" +
        '<span class="eyebrow" style="margin-top:14px">Most common flags</span>' +
        (Object.keys(tags).length
          ? hbars(Object.keys(tags).sort(function (x, y) { return tags[y] - tags[x]; }).slice(0, 4).map(function (k) {
              return { label: tagLabel(k), value: tags[k], display: String(tags[k]), warm: true }; }), { plain: true })
          : '<p class="muted small">None recorded.</p>') +
        "</div></div>" +
        '<details class="disclosure" style="margin-top:6px"><summary>Market conditions</summary>' +
        hbars(Object.keys(regime).map(function (k) {
          return { label: k + " sessions", value: regime[k], display: String(regime[k]) }; }), { plain: true }) +
        "</details></section>";
    }).join("");

    return '<div class="page-head"><div class="grow">' +
      '<span class="eyebrow">Registry</span><h1>Strategies</h1>' +
      '<p class="page-sub">Every record points at the version that was in force at the time. ' +
      "Editing a strategy publishes a new version; it never rewrites history.</p></div></div>" +
      '<div class="stack">' + cards + "</div>" +
      '<div class="warnband" style="margin-top:20px"><span class="g">by design</span>' +
      "<p>Blinded research variables are not sliceable from this screen. Strategy performance here is " +
      "market and behaviour only. See <a href=\"#/research\">Research Mode</a>.</p></div>";
  }

  /* ------------------------------------------------------------------ view: RESEARCH */
  var researchUnlocked = false;

  function viewResearch() {
    if (!researchUnlocked) {
      return '<div class="page-head"><div class="grow">' +
        '<span class="eyebrow">Restricted</span><h1>Research Mode</h1>' +
        '<p class="page-sub">Blinded variables live here and nowhere else.</p></div></div>' +
        '<div class="locked"><h2 style="margin-bottom:10px">This section is blinded on purpose</h2>' +
        '<p class="prose" style="max-width:56ch;margin:0 auto 20px">Personal and market research features are ' +
        "computed for every session and stored, but they are never shown during check-in, check-out or daily " +
        "review. The point is to keep your expectations out of your own data. Opening this section writes an " +
        "entry to the unblinding log with a timestamp and a reason.</p>" +
        '<button class="btn btn-primary" data-unlock="1">Enter Research Mode</button>' +
        '<p class="small muted" style="margin-top:14px">Prototype: no real features are revealed.</p></div>';
    }

    var samples = D.research.sample_sizes;
    var prereg = D.research.preregistrations;
    var sessionsN = SESSIONS.length;

    return '<div class="page-head"><div class="grow">' +
      '<span class="eyebrow">Research Mode · unblinded session</span><h1>Research Mode</h1>' +
      '<p class="page-sub">Opened ' + esc(D.meta.generated_at) + " · logged</p></div>" +
      '<button class="btn" data-unlock="0">Leave and re-blind</button></div>' +

      '<div class="warnband" style="margin-bottom:20px"><span class="g">n = ' + sessionsN + "</span>" +
      "<p><b>Sample sizes here do not support conclusions.</b> With " + sessionsN + " sessions, any subgroup " +
      "you can name has fewer than 30 observations. This screen deliberately shows counts before it shows " +
      "effects, and it will not compute an effect for a feature below its preregistered minimum n.</p></div>" +

      '<div class="grid g-main"><div class="stack">' +
      '<section class="card"><div class="card-head"><span class="eyebrow">Feature sets</span>' +
      '<span class="muted small">keys are opaque by design</span></div>' +
      '<div class="table-wrap"><table><thead><tr><th>Set</th><th>Key</th><th class="n">n</th>' +
      '<th>Status</th><th>Label</th></tr></thead><tbody>' +
      samples.map(function (r) {
        return "<tr><td>" + esc(r.feature_set) + '</td><td class="num">' + esc(r.feature_key) + "</td>" +
          '<td class="n">' + r.n_observations + "</td><td>" +
          '<span class="chip ' + (r.sample_status === "reportable" ? "chip-accent" :
            r.sample_status === "provisional" ? "chip-watch" : "chip-flag") + '">' + esc(r.sample_status) + "</span></td>" +
          '<td><span class="redacted">withheld until preregistered</span></td></tr>';
      }).join("") + "</tbody></table></div>" +
      '<p class="small muted" style="margin-top:12px">Feature labels are stored in a separate dictionary ' +
      "table and are only joined under a locked preregistration. Values are visible; meanings are not.</p></section>" +

      '<section class="card"><div class="card-head"><span class="eyebrow">Preregistered questions</span>' +
      '<button class="btn" disabled style="opacity:.55;cursor:not-allowed">New question</button></div>' +
      '<div class="stack-sm">' + prereg.map(function (p) {
        return '<div class="reflect-item"><span class="k">' + esc(p.status) + " · min n " + p.min_n +
          " · outcome " + esc(p.outcome_metric) + '</span><span class="t">' + esc(p.question) + "</span>" +
          '<p class="small muted" style="margin-top:4px">' + esc(p.hypothesis) + "</p></div>";
      }).join("") + "</div>" +
      '<p class="small muted" style="margin-top:12px">A question must be locked before the data is looked at. ' +
      "The lock stores a hash of the analysis plan so it cannot be edited after seeing the result.</p></section>" +

      '<section class="card"><div class="card-head"><span class="eyebrow">Available analyses</span></div>' +
      '<div class="stack-sm">' + [
        ["Personal state vs execution quality", sessionsN, 120],
        ["Personal state vs rule violations", sessionsN, 120],
        ["Sleep and focus vs mistake count", sessionsN, 60],
        ["Manual intervention vs mechanical outcome", 90, 100],
        ["Strategy vs market regime", sessionsN, 200]
      ].map(function (row) {
        var ok = row[1] >= row[2];
        return '<div class="rating"><span class="lbl">' + esc(row[0]) +
          '<br><span class="muted small">n = ' + row[1] + " · needs " + row[2] + "</span></span>" +
          '<span class="chip ' + (ok ? "chip-accent" : "chip-watch") + '">' +
          (ok ? "runnable" : "under-powered") + "</span></div>";
      }).join("") + "</div></section>" +
      "</div><div class=\"stack\">" +
      '<section class="card"><div class="card-head"><span class="eyebrow">Unblinding log</span></div>' +
      '<p class="muted small">No unblinding events recorded. This prototype does not reveal features; ' +
      "in the real system every entry into this mode is written here with actor, scope and reason.</p></section>" +
      '<section class="card"><div class="card-head"><span class="eyebrow">Rules of this room</span></div>' +
      '<div class="reflect">' +
      '<div class="reflect-item"><span class="k">1</span><span class="t">Questions are written down before the data is looked at.</span></div>' +
      '<div class="reflect-item"><span class="k">2</span><span class="t">No weekly automatic slicing. Nothing here runs on a schedule.</span></div>' +
      '<div class="reflect-item"><span class="k">3</span><span class="t">Findings below the preregistered n are not shown, not even greyed out.</span></div>' +
      '<div class="reflect-item"><span class="k">4</span><span class="t">Nothing from this screen is ever surfaced during a trading session.</span></div>' +
      "</div></section></div></div>";
  }

  /* ------------------------------------------------------------------ view: CAPTURE */
  function viewCapture() {
    return '<div class="page-head"><div class="grow">' +
      '<span class="eyebrow">Mobile intake</span><h1>Capture</h1>' +
      '<p class="page-sub">The two moments that have to be frictionless. Everything else in this ' +
      "journal can be reconstructed from data; these cannot.</p></div></div>" +

      '<div class="phones">' +
      '<div><div class="phone"><div class="phone-screen">' +
        '<div class="phone-status"><span>9:10</span><span>Pre-session</span></div>' +
        '<div class="notif"><div><span class="src">Trading Journal</span>' +
        "<p><b>Twenty minutes to the open.</b> Thirty seconds — how are you arriving today?</p></div></div>" +
        '<div class="stack-sm">' +
        slider("Sleep", "sleep", 6.2, 3, 10, 0.1, " h") +
        slider("Energy", "energy", 3, 1, 5, 1, "/5") +
        slider("Focus", "focus", 4, 1, 5, 1, "/5") +
        slider("Stress", "stress", 2, 1, 5, 1, "/5") +
        slider("Desire to trade", "desire", 3, 1, 5, 1, "/5") +
        "</div>" +
        '<div><span class="eyebrow">Bias</span><div class="seg" data-seg="bias">' +
        ["Bullish", "Neutral", "Bearish"].map(function (b, i) {
          return "<button aria-pressed=\"" + (i === 1) + "\">" + b + "</button>"; }).join("") + "</div></div>" +
        '<div><span class="eyebrow">A well-traded day today means</span>' +
        '<textarea class="note" rows="2">Only A-setups. Two trades maximum.</textarea></div>' +
        '<details class="disclosure"><summary>More (optional)</summary>' +
        '<div class="stack-sm">' + slider("Impulsivity", "imp", 2, 1, 5, 1, "/5") +
        slider("Confidence", "conf", 4, 1, 5, 1, "/5") +
        '<div class="rating"><span class="lbl">Pressure to make money</span>' +
        '<div class="seg" data-seg="press" style="width:110px"><button aria-pressed="false">Yes</button>' +
        '<button aria-pressed="true">No</button></div></div></div></details>' +
        '<button class="btn btn-primary" style="justify-content:center">Save and start the day</button>' +
        '<p class="small muted center">Median completion in the prototype: 41 seconds.</p>' +
      "</div></div>" +
      '<p class="phone-caption"><b>Morning.</b> Five sliders, one segmented control, one sentence. ' +
      "Everything else is behind “More”. The one required free-text field is the definition of a " +
      "well-traded day, because it is what the evening check-out is scored against.</p></div>" +

      '<div><div class="phone"><div class="phone-screen">' +
        '<div class="phone-status"><span>16:05</span><span>Post-session</span></div>' +
        '<div class="notif"><div><span class="src">Trading Journal</span>' +
        "<p><b>Session closed.</b> 2 trades, 3 qualified setups. Two minutes to close the day.</p></div></div>" +
        '<div class="stack-sm">' +
        slider("Execution quality", "exq", 4, 1, 5, 1, "/5") +
        slider("Rule adherence", "adh", 4, 1, 5, 1, "/5") +
        slider("Patience", "pat", 3, 1, 5, 1, "/5") +
        slider("Emotional control", "emo", 4, 1, 5, 1, "/5") +
        "</div>" +
        '<div><span class="eyebrow">Anything happen?</span><div class="checks">' +
        ["Overtraded", "Revenge trade", "Stop moved", "Oversized", "Missed a setup", "Overrode a rule"]
          .map(function (c, i) {
            return '<button class="check" aria-pressed="' + (i === 4) + '"><span class="box"></span>' + c + "</button>";
          }).join("") + "</div></div>" +
        '<div><span class="eyebrow">Would this be a well-traded day with P&amp;L hidden?</span>' +
        '<div class="seg" data-seg="wt">' + ["Yes", "Mixed", "No"].map(function (b, i) {
          return "<button aria-pressed=\"" + (i === 1) + "\">" + b + "</button>"; }).join("") + "</div></div>" +
        '<button class="mic"><span class="dot"></span><span class="t">Hold to record a voice note</span>' +
        '<span class="num">0:48</span></button>' +
        '<button class="btn btn-primary" style="justify-content:center">Finish session</button>' +
        '<p class="small muted center">Best decision and biggest mistake are asked on the next card.</p>' +
      "</div></div>" +
      '<p class="phone-caption"><b>Evening.</b> Four ratings, six checkboxes, one verdict, one optional ' +
      "voice note. The mistake checkboxes write straight into the taxonomy; the voice note is stored as " +
      "audio plus verbatim transcript and is never edited by a model.</p></div>" +
      "</div>" +

      '<section class="card" style="margin-top:28px"><div class="card-head">' +
      '<span class="eyebrow">How the prompt arrives</span></div>' +
      '<div class="grid g-3">' +
      ["A scheduled job on your machine (launchd / cron / Task Scheduler) fires at 09:10 and 16:05 ET " +
       "and posts a notification. Nothing needs to be running or watching.",
       "The notification opens the local web app straight onto the form for that session — no navigation, " +
       "no login, no picking a date.",
       "If a check-in is skipped, the session is still created and marked incomplete. Missing data is " +
       "recorded as missing, never back-filled from memory a week later."
      ].map(function (t, i) {
        return '<div class="reflect-item"><span class="k">Step ' + (i + 1) + '</span><span class="t" ' +
          'style="font-size:14.5px">' + esc(t) + "</span></div>";
      }).join("") + "</div></section>";
  }

  function slider(label, id, value, min, max, step, unit) {
    return '<div class="slider-row"><div class="top"><span class="lbl">' + esc(label) + "</span>" +
      '<span class="val" data-out="' + id + '">' + value + esc(unit) + "</span></div>" +
      '<input type="range" data-slider="' + id + '" data-unit="' + esc(unit) + '" min="' + min +
      '" max="' + max + '" step="' + step + '" value="' + value + '" aria-label="' + esc(label) + '"></div>';
  }

  /* ------------------------------------------------------------------ router */
  var ROUTES = [
    ["#/today", "Today", "◈"], ["#/calendar", "History", "▦"], ["#/weekly", "Weekly", "▤"],
    ["#/monthly", "Monthly", "▥"], ["#/strategies", "Strategies", "◇"], ["#/capture", "Capture", "✎"]
  ];

  function render() {
    var hash = location.hash || "#/today";
    var parts = hash.split("/");
    var main = document.getElementById("view");
    var html;

    if (parts[1] === "session") html = viewSession(parts[2]);
    else if (parts[1] === "trade") html = viewTrade(parts[2]);
    else if (parts[1] === "calendar") html = viewCalendar();
    else if (parts[1] === "weekly") html = viewWeekly();
    else if (parts[1] === "monthly") html = viewMonthly();
    else if (parts[1] === "strategies") html = viewStrategies();
    else if (parts[1] === "research") html = viewResearch();
    else if (parts[1] === "capture") html = viewCapture();
    else html = viewToday();

    main.innerHTML = '<div class="view">' + html + "</div>";
    main.scrollTop = 0;
    window.scrollTo(0, 0);

    var current = "#/" + (parts[1] || "today");
    [].forEach.call(document.querySelectorAll("[data-nav]"), function (a) {
      var match = a.getAttribute("href") === current ||
        (current === "#/session" && a.getAttribute("href") === "#/calendar") ||
        (current === "#/trade" && a.getAttribute("href") === "#/calendar");
      if (match) a.setAttribute("aria-current", "page");
      else a.removeAttribute("aria-current");
    });
    wireCharts();
  }

  /* crosshair + tooltip for every chart that declares hot zones */
  function wireCharts() {
    [].forEach.call(document.querySelectorAll(".chart-wrap[data-chart]"), function (wrap) {
      var tip = wrap.querySelector(".tooltip");
      var svg = wrap.querySelector("svg");
      var cross = svg.querySelector(".cross");
      if (!tip || !svg) return;
      [].forEach.call(svg.querySelectorAll("[data-label]"), function (node) {
        node.addEventListener("mouseenter", function () {
          var box = svg.getBoundingClientRect();
          var vb = svg.viewBox.baseVal;
          var scale = box.width / vb.width;
          var cx = +node.getAttribute("data-cx") * scale;
          var cy = +node.getAttribute("data-cy") * scale;
          tip.textContent = node.getAttribute("data-label");
          tip.style.left = cx + "px";
          tip.style.top = (cy - 8) + "px";
          tip.classList.add("on");
          if (cross) {
            cross.setAttribute("x1", node.getAttribute("data-cx"));
            cross.setAttribute("x2", node.getAttribute("data-cx"));
            cross.setAttribute("opacity", "1");
          }
        });
      });
      wrap.addEventListener("mouseleave", function () {
        tip.classList.remove("on");
        if (cross) cross.setAttribute("opacity", "0");
      });
    });
  }

  /* ------------------------------------------------------------------ interactions */
  document.addEventListener("click", function (e) {
    var t = e.target.closest ? e.target.closest("[data-daystate],[data-week],[data-month],[data-cal]," +
      "[data-unlock],[data-tl],[data-theme-btn],.seg button,.check") : null;
    if (!t) return;

    if (t.hasAttribute("data-daystate")) { dayState = t.getAttribute("data-daystate"); render(); return; }
    if (t.hasAttribute("data-week")) { weekKey = t.getAttribute("data-week"); render(); return; }
    if (t.hasAttribute("data-month")) { monthKey = t.getAttribute("data-month"); render(); return; }
    if (t.hasAttribute("data-cal")) { calMonth = t.getAttribute("data-cal"); render(); return; }
    if (t.hasAttribute("data-unlock")) { researchUnlocked = t.getAttribute("data-unlock") === "1"; render(); return; }
    if (t.hasAttribute("data-theme-btn")) { toggleTheme(); return; }
    if (t.hasAttribute("data-tl")) {
      var panel = document.getElementById("tl-" + t.getAttribute("data-tl"));
      var open = t.getAttribute("aria-expanded") === "true";
      t.setAttribute("aria-expanded", String(!open));
      if (panel) panel.hidden = open;
      return;
    }
    if (t.classList.contains("check")) {
      t.setAttribute("aria-pressed", t.getAttribute("aria-pressed") === "true" ? "false" : "true");
      return;
    }
    if (t.parentElement && t.parentElement.classList.contains("seg")) {
      [].forEach.call(t.parentElement.children, function (b) { b.setAttribute("aria-pressed", "false"); });
      t.setAttribute("aria-pressed", "true");
    }
  });

  document.addEventListener("input", function (e) {
    var s = e.target;
    if (!s.hasAttribute || !s.hasAttribute("data-slider")) return;
    var out = document.querySelector('[data-out="' + s.getAttribute("data-slider") + '"]');
    if (out) out.textContent = s.value + s.getAttribute("data-unit");
  });

  function toggleTheme() {
    var root = document.documentElement;
    var now = root.getAttribute("data-theme");
    var prefersDark = window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
    var next = now ? (now === "dark" ? "light" : "dark") : (prefersDark ? "light" : "dark");
    root.setAttribute("data-theme", next);
    var btn = document.querySelector("[data-theme-btn] .theme-state");
    if (btn) btn.textContent = next === "dark" ? "Dark" : "Light";
  }

  /* ------------------------------------------------------------------ chrome */
  function chrome() {
    var nav = ROUTES.map(function (r) {
      return '<a data-nav href="' + r[0] + '">' + r[1] + "</a>";
    }).join("");

    document.getElementById("rail").innerHTML =
      '<div class="wordmark"><b>Trading Journal</b><span>v1 prototype</span></div>' +
      '<nav class="nav">' + nav +
      '<span class="nav-group-label">Restricted</span>' +
      '<a data-nav href="#/research">Research Mode <span class="lock">blinded</span></a>' +
      "</nav>" +
      '<div class="rail-foot">' +
      '<button class="theme-toggle" data-theme-btn><span>Appearance</span>' +
      '<span class="spacer"></span><span class="theme-state num">Auto</span></button>' +
      '<p class="synthetic-note">All figures are synthetic placeholder data generated from the schema. ' +
      "No real trading records, no broker connection.</p></div>";

    document.getElementById("topbar").innerHTML =
      "<b>Trading Journal</b>" +
      '<p class="synthetic-note">synthetic data</p>';

    document.getElementById("tabbar").innerHTML =
      [["#/today", "Today", "◈"], ["#/calendar", "History", "▦"], ["#/weekly", "Weekly", "▤"],
       ["#/strategies", "Setups", "◇"], ["#/capture", "Capture", "✎"]].map(function (r) {
        return '<a data-nav href="' + r[0] + '"><span class="g" aria-hidden="true">' + r[2] +
          "</span>" + r[1] + "</a>";
      }).join("");
  }

  chrome();
  window.addEventListener("hashchange", render);
  render();
})();
